//
//  CountryDetailRouter.swift
//  CovidApp
//
//  Created by Joan Martin Martrus on 22/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CountryDetailRoutingLogic
{
  //func navigateToAnotherScreen(withParameter: model)
}

class CountryDetailRouter: NSObject, CountryDetailRoutingLogic
{
  weak var viewController: CountryDetailViewController?
  
  // MARK: Routing
      
//    func navigateToExampleViewController(withParameters:Model) {
//        let vc = ExampleViewController()
//        vc.model = model
//        viewController?.show(vc, sender: nil)
//    }
}
