//
//  CountryDetailViewController.swift
//  CovidApp
//
//  Created by Joan Martin Martrus on 22/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryDetailDisplayLogic: class
{
    func showError(error: Error)
}

class CountryDetailViewController: BaseViewController, CountryDetailDisplayLogic
{
    var interactor: CountryDetailBusinessLogic?
    var router: (NSObjectProtocol & CountryDetailRoutingLogic)?
    
    // MARK: IBoutlets
    
    
    // MARK: Properties
    
    var countryName: String?
    
    // MARK: CountryDetailDisplayLogic protocol implementation
    
    func showError(error: Error) {
        self.removeSpinner()
        self.showErrorAlert(error: error)
    }

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
  
  // MARK: Setup
  
    private func setup()
    {
        let viewController = self
        let interactor = CountryDetailInteractor()
        let presenter = CountryDetailPresenter()
        let router = CountryDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        beginLoadInfo()
    }
    
    private func beginLoadInfo() {
        self.showSpinner(onView: self.view)
        if let countryName = self.countryName {
            interactor?.getCountryInfo(countryName: countryName, date: "06-05-2020")
        }
    }
  
}
