//
//  SearchCountryPresenter.swift
//  CovidApp
//
//  Created by Joan Martin Martrus on 21/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCountryPresentationLogic
{
    func onDataLoadSucceed(countriesCovidInfo: [CountryCovidInfoResponse])
    func onDataLoadError(error: Error)
}

class SearchCountryPresenter: SearchCountryPresentationLogic
{
    weak var viewController: SearchCountryDisplayLogic?
    
    // MARK: SearchCountryPresentationLogic protocol implementation
    
    func onDataLoadSucceed(countriesCovidInfo: [CountryCovidInfoResponse]) {
        var cellModels: [DrawerItemProtocol] = []
        countriesCovidInfo.forEach { (countryCovidInfo) in
            cellModels.append(CountryCovidInfoCellViewModel.init(countryCovidInfo: countryCovidInfo))
        }
        viewController?.showData(cellModels: cellModels)
    }
    
    func onDataLoadError(error: Error) {
        viewController?.showError(error: error)
    }
  
  
}
