//
//  SearchCountryInteractor.swift
//  CovidApp
//
//  Created by Joan Martin Martrus on 21/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCountryBusinessLogic
{
    func getCountriesCovidInfo()
}

class SearchCountryInteractor: SearchCountryBusinessLogic
{

    
    var presenter: SearchCountryPresentationLogic?
    //var service: ItemService()
    
    func getCountriesCovidInfo() {
        NetworkDispatcher.request(endpoint: CovidInfoEndpoint.getCountryList) { (result: Result<[CountryCovidInfo], Error>) in
            switch result {
            case .success(let response):
                self.presenter?.onDataLoadSucceed(countriesCovidInfo: response)
            case .failure(let error):
                self.presenter?.onDataLoadError(error: error)
            }
        }
    }
    
  
}
