//
//  SearchCountryViewController.swift
//  CovidApp
//
//  Created by Joan Martin Martrus on 21/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCountryDisplayLogic: class
{
    func showData(cellModels: [DrawerItemProtocol])
    func showError(error: Error)
}

class SearchCountryViewController: BaseViewController, SearchCountryDisplayLogic
{

    var interactor: SearchCountryBusinessLogic?
    var router: (NSObjectProtocol & SearchCountryRoutingLogic)?
    
    // MARK: IBoutlets
    
    @IBOutlet var tableView: UITableView!
    
    // MARK: Properties
    
    var cellModels: [DrawerItemProtocol] = []
    
    // MARK: SearchCountryDisplayLogic protocol implementatios
    
    func showData(cellModels: [DrawerItemProtocol]) {
        self.cellModels = cellModels
        tableView.reloadData()
    }
    
    func showError(error: Error) {
        self.showErrorAlert(error: error)
    }
    
    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup()
    {
        let viewController = self
        let interactor = SearchCountryInteractor()
        let presenter = SearchCountryPresenter()
        let router = SearchCountryRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        tableView.delegate = self
        tableView.dataSource = self
        
        interactor?.getCountriesCovidInfo()
    }
  
}

extension SearchCountryViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return cellModels.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cellModel = cellModels[indexPath.row]
        let drawer = cellModel.cellDrawer
        let cell = drawer.dequeueCell(tableView, cellForRowAt: indexPath)
        drawer.drawCell(cell, withItem: cellModel, delegate: self, at: indexPath)
        return cell
    }
    
    
}
