//
//  SearchCountryRouter.swift
//  CovidApp
//
//  Created by Joan Martin Martrus on 21/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCountryRoutingLogic
{
    func navigateToCountryDetailViewController(withParameters: CountryCovidInfoResponse)
}

class SearchCountryRouter: SearchCountryRoutingLogic
{

  weak var viewController: SearchCountryViewController?
  
    // MARK: Routing
      
    func navigateToCountryDetailViewController(withParameters: CountryCovidInfoResponse) {
        let vc = CountryDetailViewController()
        vc.countryName = withParameters.country
        viewController?.navigationController?.show(vc, sender: nil)
    }
    

}
